### ISSUE TITLE
Metapackage named as dependency

### ISSUE THREAD

**Issue by p-snft** [oemof/oemof-thermal#124] opened 2020-06-05 18:32 UTC
With the release of solph v0.4, the result should be oemof.solph instead of oemof.

**Comment by jnnr** [comment] 2020-06-17 07:52
This might be the cause of [issue #708](https://github.com/oemof/oemof-solph/issues/708) on oemof.solph. Before closing, please check if this has been resolved as well.

**Closed as completed** 2020-07-01 16:26 UTC
